import {useEffect,useRef,useState} from 'react';
import {CheckCircle2,Database,Download,FileArchive,FlaskConical,RefreshCw,Trash2,Upload} from 'lucide-react';
import {deleteEngine,downloadEnginePackage,getActiveEngine,listEngines,registerEnginePackage,setActiveEngineId,type EngineDef,type RegressionCase} from '../../services/engineRegistry';
import {StatusBadge} from '../../ui/StatusBadge';
import {useToast} from '../../ui/Toast';
import type {RegressionLaunch} from '../checker/CheckerPage';

export function SettingsPage({onStartRegression}:{onStartRegression?:(launch:RegressionLaunch)=>void}){
 const toast=useToast();const fileRef=useRef<HTMLInputElement>(null);const[engines,setEngines]=useState<EngineDef[]>([]);const[active,setActive]=useState('');const[busy,setBusy]=useState(false);const[dragging,setDragging]=useState(false);const[detail,setDetail]=useState<string|null>(null);const[expectedOpen,setExpectedOpen]=useState<string|null>(null);
 async function refresh(){setEngines(await listEngines());setActive((await getActiveEngine()).id)}
 useEffect(()=>{refresh();const f=()=>refresh();window.addEventListener('vdf-engine-change',f);window.addEventListener('vdf-engine-registry-change',f);return()=>{window.removeEventListener('vdf-engine-change',f);window.removeEventListener('vdf-engine-registry-change',f)}},[]);
 async function apply(id:string){setActiveEngineId(id);setActive(id);toast.push(`${engines.find(e=>e.id===id)?.label||id} 엔진을 ACTIVE로 적용했습니다.`,'success')}
 async function importFile(file?:File){if(!file)return;try{setBusy(true);const engine=await registerEnginePackage(file);toast.push(`${engine.label} 패키지를 등록했습니다. ACTIVE 전환은 별도로 해주세요.`,'success');await refresh()}catch(e){toast.push(e instanceof Error?e.message:'엔진 패키지 등록에 실패했습니다.','error')}finally{setBusy(false);if(fileRef.current)fileRef.current.value=''}}
 async function remove(id:string){if(!confirm('등록된 엔진을 삭제할까요?'))return;try{await deleteEngine(id);toast.push('엔진 패키지를 삭제했습니다.','success');await refresh()}catch(e){toast.push(e instanceof Error?e.message:'삭제할 수 없습니다.','error')}}
 async function download(engine:EngineDef){try{await downloadEnginePackage(engine);toast.push(`${engine.label} 엔진 ZIP을 저장했습니다.`,'success')}catch(e){toast.push(e instanceof Error?e.message:'엔진 ZIP을 만들지 못했습니다.','error')}}
 function startTest(engine:EngineDef,test:RegressionCase){if(test.status==='REFERENCE_ONLY'||!test.input.trim()){toast.push('이 케이스는 Historical Reference 전용이며 실행 입력이 확보되지 않았습니다.','info');return}if(active!==engine.id){setActiveEngineId(engine.id);setActive(engine.id);toast.push(`${engine.label}을 테스트용 ACTIVE 엔진으로 적용했습니다.`,'success')}onStartRegression?.({engineId:engine.id,engineLabel:engine.label,test,nonce:Date.now()})}
 const activeEngine=engines.find(e=>e.id===active);
 return <div className="page settings-page">
  <header className="page-head"><p className="eyebrow">ENGINE PACKAGE REGISTRY</p><h1>VDF 엔진 관리</h1><p>배포 기준 엔진은 VDF 6.0.0 Reference / Stable / Freeze입니다. 필요할 때만 별도 엔진 ZIP을 등록해 시험할 수 있으며 등록만으로 ACTIVE가 바뀌지 않습니다.</p></header>
  <section className="panel canonical-lock"><div><Database size={22}/><div><b>현재 ACTIVE 엔진</b><p>{activeEngine?.label||'VDF 6.0 Reference / Stable'} · {activeEngine?.version}</p></div></div><StatusBadge tone="success">ACTIVE</StatusBadge></section>
  <section className="panel canonical-lock"><div><CheckCircle2 size={22}/><div><b>Release Freeze</b><p>Production 기본값은 VDF 6.0.0입니다. 실험 후보는 배포 런타임에 포함하지 않습니다.</p></div></div><StatusBadge tone="success">6.0.0</StatusBadge></section>

  <section className="panel engine-import-panel"><div className="panel-head"><div><p className="eyebrow">OPTIONAL REGISTER</p><h2>외부 엔진 패키지 등록</h2></div><FileArchive/></div><p>고급 검증용입니다. ZIP 안의 manifest.json, rules.json, VDF 규칙/지시문, contract.json을 확인해 등록합니다.</p>
   <input ref={fileRef} type="file" accept=".zip,application/zip" hidden onChange={e=>importFile(e.target.files?.[0])}/>
   <div className={`engine-dropzone ${dragging?'dragging':''}`} onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={e=>{e.preventDefault();setDragging(false)}} onDrop={e=>{e.preventDefault();setDragging(false);importFile(e.dataTransfer.files?.[0])}}><Upload/><div><b>VDF Engine ZIP을 여기에 놓으세요</b><span>등록 후 자동으로 ACTIVE가 되지 않습니다.</span></div><button className="button primary" disabled={busy} onClick={()=>fileRef.current?.click()}>{busy?'검증 중…':'ZIP 선택'}</button></div>
  </section>

  <div className="engine-grid">{engines.map(e=><section className={`panel engine-card ${active===e.id?'engine-active':''}`} key={e.id}>
   <div className="panel-head"><div><p className="eyebrow">{e.source==='BUILT_IN'?'BUILT-IN':'PACKAGE'}</p><h2>{e.label}</h2></div><StatusBadge tone={e.status==='STABLE'?'success':e.status==='HOLD'?'warning':e.status==='CANDIDATE'?'warning':'info'}>{e.source==='BUILT_IN'?'REFERENCE / STABLE':e.status}</StatusBadge></div>
   <dl className="engine-meta"><div><dt>Version</dt><dd>{e.version}</dd></div><div><dt>등록일</dt><dd>{e.registeredAt.slice(0,10)}</dd></div><div><dt>Rules</dt><dd><code>{e.rulesHash.slice(0,14)}…</code></dd></div><div><dt>Instruction</dt><dd><code>{e.instructionHash.slice(0,14)}…</code></dd></div><div><dt>Contract</dt><dd><code>{e.contractHash.slice(0,14)}…</code></dd></div><div><dt>Regression</dt><dd><StatusBadge tone={e.regressionCases.length?'success':'warning'}>{e.regressionCases.length} CASES</StatusBadge></dd></div></dl>
   {detail===e.id&&<div className="engine-details"><div className="engine-file-summary"><b>Package contents</b><span>manifest.json</span><span>rules.json</span><span>VDF6_규칙.md</span><span>VDF6_지시문.md</span><span>contract.json</span><span>regression/ · {e.regressionCases.length} cases</span></div><b>Manifest</b><pre>{JSON.stringify(e.manifest,null,2)}</pre>
    <div className="regression-browser"><div className="panel-head"><div><p className="eyebrow">REGRESSION BROWSER</p><h3>이 엔진의 테스트 케이스</h3></div><StatusBadge tone={e.regressionCases.length?'success':'warning'}>{e.regressionCases.length}</StatusBadge></div>{e.regressionCases.length?e.regressionCases.map(test=><article className="regression-case" key={test.id}><div className="regression-case-head"><div><b>{test.id} · {test.name}</b><p>{test.purpose||'저장된 expected 기준으로 엔진 결과를 확인합니다.'}</p></div><StatusBadge tone={test.status==='GOLDEN'?'success':test.status==='CANDIDATE'?'warning':'info'}>{test.status}</StatusBadge></div><div className="action-row"><button className="button primary" disabled={test.status==='REFERENCE_ONLY'||!test.input.trim()} onClick={()=>startTest(e,test)}><FlaskConical size={16}/>{test.status==='REFERENCE_ONLY'?'Reference 전용':'이 엔진으로 테스트'}</button><button className="button secondary" onClick={()=>setExpectedOpen(expectedOpen===`${e.id}:${test.id}`?null:`${e.id}:${test.id}`)}>Expected {expectedOpen===`${e.id}:${test.id}`?'닫기':'보기'}</button></div>{expectedOpen===`${e.id}:${test.id}`&&<pre className="expected-json">{JSON.stringify(test.expected,null,2)}</pre>}</article>):<p className="field-help">이 패키지에는 regression case가 없습니다.</p>}</div>
   </div>}
   <div className="action-row engine-actions"><button className="button secondary" onClick={()=>setDetail(detail===e.id?null:e.id)}>{detail===e.id?'상세 닫기':'상세 / 테스트'}</button><button className="button secondary" onClick={()=>download(e)}><Download size={17}/>엔진 ZIP 다운로드</button>{active===e.id?<button className="button secondary" disabled><CheckCircle2 size={17}/>현재 적용 중</button>:<button className="button primary" onClick={()=>apply(e.id)}><RefreshCw size={17}/>이 엔진을 ACTIVE로 적용</button>}{e.source==='PACKAGE'&&<button className="button ghost danger-button" disabled={active===e.id} aria-label={`${e.label} 삭제`} title={active===e.id?'ACTIVE 엔진은 삭제할 수 없습니다.':''} onClick={()=>remove(e.id)}><Trash2 size={17}/></button>}</div>
  </section>)}</div>
  <section className="panel"><div className="panel-head"><div><p className="eyebrow">POLICY</p><h2>Release 운영 원칙</h2></div><FlaskConical size={22}/></div><p>6.0.0을 기본 엔진으로 사용합니다. 규칙 변경은 별도 Candidate 패키지로 검증하고 기존 성공 케이스를 회귀검증한 뒤에만 다음 Stable 버전으로 승격합니다.</p></section>
 </div>
}
